### ISSUE TITLE
AttributeError: module 'random' has no attribute 'choices'

### ISSUE THREAD

**Issue by mcam1551** [zhzyker/vulmap#42]
In python 3.5 random.choices() will fail because that method is not available on python 3.5.

Replacing random.choices() with random.sample() will work on python 3.5.

Adding a routine to check for python version and use one or the other works as well.

**Comment by zhzyker** [comment]
In fact vulmap is designed for > python 3.7
At least python 3.6 is also required, but there is a problem with gevent in python 3.6
So it is not compatible with python 3.5

Thanks for your feedback
